//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Agency
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Agency()
    {
        this.Clients = new HashSet<Client>();
    }

    public int ID { get; set; }
    public string name { get; set; }
    public string hebrew { get; set; }
    public string address { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Client> Clients { get; set; }
}

public partial class Client
{
    public string PNR { get; set; }
    public string names { get; set; }
    public int PAX { get; set; }
    public string num_arr { get; set; }
    public System.DateTime date_arr { get; set; }
    public string num_dep { get; set; }
    public Nullable<System.DateTime> date_dep { get; set; }
    public string phone { get; set; }
    public int hotel_fk { get; set; }
    public int agency_fk { get; set; }
    public Nullable<bool> oneway { get; set; }
    public bool canceled { get; set; }
    public string comments { get; set; }
    public System.DateTime date_update { get; set; }
    public string depart_list { get; set; }
    public string arrival_list_fk { get; set; }

    public virtual Agency Agency { get; set; }
    public virtual Flight Flight { get; set; }
    public virtual Flight Flight1 { get; set; }
    public virtual Client Clients1 { get; set; }
    public virtual Client Client1 { get; set; }
    public virtual Flight Flight2 { get; set; }
    public virtual Flight Flight3 { get; set; }
}

public partial class DepartPlan
{
    public string depart_list { get; set; }
    public int hotel_fk { get; set; }
    public Nullable<System.DateTime> date_dep_start { get; set; }
    public Nullable<System.TimeSpan> time { get; set; }
    public int PAX { get; set; }
}

public partial class Flight
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Flight()
    {
        this.Clients = new HashSet<Client>();
        this.Clients1 = new HashSet<Client>();
        this.Clients2 = new HashSet<Client>();
        this.Clients3 = new HashSet<Client>();
    }

    public string num { get; set; }
    public System.DateTime date { get; set; }
    public string time { get; set; }
    public string destination { get; set; }
    public string direction { get; set; }
    public Nullable<System.TimeSpan> time_approved { get; set; }
    public Nullable<System.DateTime> date_update { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Client> Clients { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Client> Clients1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Client> Clients2 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Client> Clients3 { get; set; }
}

public partial class Guide
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Guide()
    {
        this.TourPlans = new HashSet<TourPlan>();
    }

    public int ID { get; set; }
    public string name { get; set; }
    public string phone { get; set; }
    public string role { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TourPlan> TourPlans { get; set; }
}

public partial class Hotel
{
    public int ID { get; set; }
    public string name { get; set; }
    public string address { get; set; }
    public string meeting_point { get; set; }
    public string city { get; set; }
}

public partial class Product
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {
        this.TourPlans = new HashSet<TourPlan>();
    }

    public int ID { get; set; }
    public string name { get; set; }
    public string code { get; set; }
    public string type { get; set; }
    public string hebrew { get; set; }
    public decimal rate { get; set; }
    public Nullable<int> capacity { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TourPlan> TourPlans { get; set; }
}

public partial class Sale
{
    public string PNR { get; set; }
    public int product_fk { get; set; }
    public int persons { get; set; }
    public decimal price { get; set; }
    public string sale_type { get; set; }
    public System.DateTime date_sale { get; set; }
    public System.DateTime date_update { get; set; }
    public decimal paid { get; set; }
    public bool canceled { get; set; }
    public int ID { get; set; }
    public string comments { get; set; }
    public int agency_fk { get; set; }
}

public partial class TourPlan
{
    public int ID { get; set; }
    public System.DateTime date { get; set; }
    public Nullable<System.TimeSpan> time { get; set; }
    public Nullable<int> tour_fk { get; set; }
    public Nullable<int> guide_fk { get; set; }
    public string comments { get; set; }
    public System.DateTime date_update { get; set; }
    public bool canceled { get; set; }

    public virtual Guide Guide { get; set; }
    public virtual Product Product { get; set; }
}

public partial class Upload_temp
{
    public string PNR { get; set; }
    public string names { get; set; }
    public string PAX { get; set; }
    public string num_arr { get; set; }
    public string date_arr { get; set; }
    public string num_dep { get; set; }
    public string date_dep { get; set; }
    public string phone { get; set; }
    public string hotel_name { get; set; }
    public string comments { get; set; }
    public int ID { get; set; }
}
